version: '3.8'
services:
  db:
    image: postgres:15
    container_name: truvi_postgres
    environment:
      POSTGRES_USER: truvi
      POSTGRES_PASSWORD: truvi
      POSTGRES_DB: truvi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
